fix for occasional `uninitialized constant Tarantool16::Connection` error in tests
problem:
- sometimes we hit the following failing tests if it runs as first test 

```ruby
  1) Error:
DumbConnection::timeouts#test_0001_should timeout on connect:
NameError: uninitialized constant Tarantool16::Connection
    /tarantool-ruby/test/test_dumb.rb:126:in `block (4 levels) in <top (required)>’
```


solution: 
- call the `DumbDB` constant to autoload it